### ISSUE TITLE
Chat messages not being sent in realtime 

### ISSUE THREAD

**Issue by serena-zhu** [serena-zhu/Matcha#120]
`message handler error
Traceback (most recent call last):
  File "/nfs/2017/y/yazhu/.brew/lib/python3.6/site-packages/engineio/server.py", line 410, in _trigger_event
    return self.handlers[event](*args)
  File "/nfs/2017/y/yazhu/.brew/lib/python3.6/site-packages/socketio/server.py", line 522, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/nfs/2017/y/yazhu/.brew/lib/python3.6/site-packages/socketio/server.py", line 458, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "/nfs/2017/y/yazhu/.brew/lib/python3.6/site-packages/socketio/server.py", line 461, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/nfs/2017/y/yazhu/.brew/lib/python3.6/site-packages/socketio/server.py", line 490, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/nfs/2017/y/yazhu/.brew/lib/python3.6/site-packages/flask_socketio/__init__.py", line 251, in _handler
    *args)
  File "/nfs/2017/y/yazhu/.brew/lib/python3.6/site-packages/flask_socketio/__init__.py", line 634, in _handle_event
    ret = handler(*args)
  File "/nfs/2017/y/yazhu/Desktop/matcha/app/chats/routes.py", line 46, in private_message
    recipient_session_id = users[payload['user_id']]`

**Comment by serena-zhu** [comment]
Casting payload['user_id'] as int to access users dictionary for recipient_session_id on the sockeio 'private_message' event fixed the issue.
